F95=gfortran
F = gcc
AR = ar

.SUFFIXES: .f90 .f

.f90.o:
	$(F95) $(FFLAGS) -c $< -o $*.o

.f.o:
	$(F) $(FFLAGS) -c $< -o $*.o

.f90.a:
	$(F95) $(FFLAGS) -Iinclude -c $< -o $*.o
	$(AR) $(ARFLAGS) $@ $*.o

.f.a:
	$(F) $(FFLAGS) -Iinclude -c $< -o $*.o
	$(AR) $(ARFLAGS) $@ $*.o

OBJS = Accept.o dpmpar.o fdavv.o fdjac.o lambda.o leastsq.o UpdateJac.o converge.o dgqt.o destsv.o

libgeolevmar.a: $(OBJS)
	$(AR) -r $@ $(OBJS)

.PHONY: clean
clean:
	-rm *.o